-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Versión del servidor:         10.4.20-MariaDB - mariadb.org binary distribution
-- SO del servidor:              Win64
-- HeidiSQL Versión:             11.3.0.6295
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Volcando estructura para tabla nueva_realidad_2021.respuestas
CREATE TABLE IF NOT EXISTS `respuestas` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `fecha` varchar(15) COLLATE utf8_unicode_ci NOT NULL,
  `nit_empresa` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `pre1_pcd` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `pre1_1_pcd` text COLLATE utf8_unicode_ci NOT NULL,
  `pre2_pcd` varchar(2) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `pre3_1_pcd` int(11) NOT NULL DEFAULT 0,
  `pre3_2_pcd` int(11) NOT NULL DEFAULT 0,
  `pre3_3_pcd` int(11) NOT NULL DEFAULT 0,
  `pre3_4_pcd` int(11) NOT NULL DEFAULT 0,
  `pre3_5_pcd` int(11) NOT NULL DEFAULT 0,
  `pre3_6_pcd` int(11) NOT NULL DEFAULT 0,
  `pre4_1_pcd` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `pre4_2_pcd` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `pre4_3_pcd` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `pre4_4_pcd` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `pre4_5_pcd` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `pre4_6_pcd` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `pre5_pcd` varchar(2) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `pre5_1_pcd` text COLLATE utf8_unicode_ci NOT NULL,
  `pre6_pcd` text COLLATE utf8_unicode_ci NOT NULL,
  `pre7_pcd` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `pre8_1_pcd` int(11) NOT NULL DEFAULT 0,
  `pre8_2_pcd` int(11) NOT NULL DEFAULT 0,
  `pre8_3_pcd` int(11) NOT NULL DEFAULT 0,
  `pre8_4_pcd` int(11) NOT NULL DEFAULT 0,
  `pre8_5_pcd` int(11) NOT NULL DEFAULT 0,
  `pre8_6_pcd` int(11) NOT NULL DEFAULT 0,
  `pre8_7_pcd` int(11) NOT NULL DEFAULT 0,
  `pre8_8_pcd` int(11) NOT NULL DEFAULT 0,
  `pre9_1_pcd` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `pre9_2_pcd` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `pre9_3_pcd` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `pre9_4_pcd` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `pre10_1_pcd` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `pre10_2_pcd` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `pre10_3_pcd` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `pre10_4_pcd` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `pre10_5_pcd` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `pre10_6_pcd` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `pre11_1_pcd` int(11) NOT NULL DEFAULT 0,
  `pre11_2_pcd` int(11) NOT NULL DEFAULT 0,
  `pre11_3_pcd` int(11) NOT NULL DEFAULT 0,
  `pre11_4_pcd` int(11) NOT NULL DEFAULT 0,
  `pre12_pcd` text COLLATE utf8_unicode_ci NOT NULL,
  `pre13_pcd` text COLLATE utf8_unicode_ci NOT NULL,
  `pre14_pcd` text COLLATE utf8_unicode_ci NOT NULL,
  `pre15_pcd` text COLLATE utf8_unicode_ci NOT NULL,
  `pre16_1_pcd` int(11) NOT NULL DEFAULT 0,
  `pre16_2_pcd` int(11) NOT NULL DEFAULT 0,
  `pre16_3_pcd` int(11) NOT NULL DEFAULT 0,
  `pre16_4_pcd` int(11) NOT NULL DEFAULT 0,
  `pre17_1_pcd` varchar(2) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `pre17_2_pcd` varchar(2) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `pre1_pc` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `pre2_1_pc` int(11) NOT NULL DEFAULT 0,
  `pre2_2_pc` int(11) NOT NULL DEFAULT 0,
  `pre2_3_pc` int(11) NOT NULL DEFAULT 0,
  `pre2_4_pc` int(11) NOT NULL DEFAULT 0,
  `pre2_5_pc` int(11) NOT NULL DEFAULT 0,
  `pre3_pc` varchar(2) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `pre4_1_pc` varchar(2) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `pre4_2_pc` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `pre5_pc` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `pre6_pc` text COLLATE utf8_unicode_ci NOT NULL,
  `pre7_1_pc` int(11) NOT NULL DEFAULT 0,
  `pre7_2_pc` int(11) NOT NULL DEFAULT 0,
  `pre7_3_pc` int(11) NOT NULL DEFAULT 0,
  `pre7_4_pc` int(11) NOT NULL DEFAULT 0,
  `pre7_5_pc` int(11) NOT NULL DEFAULT 0,
  `pre7_6_pc` int(11) NOT NULL DEFAULT 0,
  `pre8_pc` text COLLATE utf8_unicode_ci NOT NULL,
  `pre9_pc` text COLLATE utf8_unicode_ci NOT NULL,
  `pre1_pi` text COLLATE utf8_unicode_ci NOT NULL,
  `pre2_pi` text COLLATE utf8_unicode_ci NOT NULL,
  `pre3_1_pi` varchar(2) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `pre3_2_pi` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `pre4_1_pi` varchar(2) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `pre4_2_pi` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `pre5_1_pi` int(11) NOT NULL DEFAULT 0,
  `pre5_2_pi` int(11) NOT NULL DEFAULT 0,
  `pre5_3_pi` int(11) NOT NULL DEFAULT 0,
  `pre5_4_pi` int(11) NOT NULL DEFAULT 0,
  `pre5_5_pi` int(11) NOT NULL DEFAULT 0,
  `pre5_6_pi` int(11) NOT NULL DEFAULT 0,
  `pre5_7_pi` int(11) NOT NULL DEFAULT 0,
  `pre6_1_pi` text COLLATE utf8_unicode_ci NOT NULL,
  `pre6_2_pi` text COLLATE utf8_unicode_ci NOT NULL,
  `pre7_pi` text COLLATE utf8_unicode_ci NOT NULL,
  `pre8_pi` text COLLATE utf8_unicode_ci NOT NULL,
  `pre1_pf` varchar(2) COLLATE utf8_unicode_ci NOT NULL,
  `pre1_1_pf` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `pre2_pf` varchar(2) COLLATE utf8_unicode_ci NOT NULL,
  `pre2_1_pf` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `pre3_1_pf` varchar(2) COLLATE utf8_unicode_ci NOT NULL,
  `pre3_2_pf` varchar(2) COLLATE utf8_unicode_ci NOT NULL,
  `pre4_pf` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `pre5_pf` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `pre6_pf` varchar(2) COLLATE utf8_unicode_ci NOT NULL,
  `pre7_pf` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `pre8_pf` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `pre9_1_pf` varchar(2) COLLATE utf8_unicode_ci NOT NULL,
  `pre9_2_pf` varchar(2) COLLATE utf8_unicode_ci NOT NULL,
  `pre10_1_pf` varchar(2) COLLATE utf8_unicode_ci NOT NULL,
  `pre10_2_pf` varchar(2) COLLATE utf8_unicode_ci NOT NULL,
  `pre11_pf` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `pre12_pf` text COLLATE utf8_unicode_ci NOT NULL,
  `pre13_pf` text COLLATE utf8_unicode_ci NOT NULL,
  `pre14_pf` text COLLATE utf8_unicode_ci NOT NULL,
  `pre15_pf` text COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=325 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- La exportación de datos fue deseleccionada.

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
